version: '3'

services:
  back:
    image: hernancr/as222s5_t09_bee:latest
    ports:
      - "8085:8085"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      RAPIDAPI_KEY: ${RAPIDAPI_KEY} 
  front:
    image: hernancr/apigptfrontend:latest
    ports:
      - "4200:4200"
    environment:
      API_BACKEND: ${API_BACKEND}
    depends_on:
      - back